-- Docker Compose now provisions the database, user, and password through
-- POSTGRES_* environment variables. Keep this file as a placeholder so
-- local setups still have a documented initialization step without
-- hardcoded credentials in version control.
